/* Indian foods with typical home/restaurant serving calories.
   Values are estimates for logging, not lab-tested nutrition facts. */
window.INDIAN_FOODS = [
  { id: "idli", name: "Idli", serving: "2 pieces", kcal: 80, p: 3, c: 16, f: 0.5, meal: ["breakfast"], diet: "veg", icon: "🍘", region: "South" },
  { id: "dosa", name: "Plain Dosa", serving: "1 dosa", kcal: 120, p: 3, c: 22, f: 3, meal: ["breakfast", "dinner"], diet: "veg", icon: "🥞", region: "South" },
  { id: "masala-dosa", name: "Masala Dosa", serving: "1 dosa", kcal: 250, p: 5, c: 38, f: 8, meal: ["breakfast", "dinner"], diet: "veg", icon: "🥞", region: "South" },
  { id: "rava-dosa", name: "Rava Dosa", serving: "1 dosa", kcal: 180, p: 4, c: 28, f: 6, meal: ["breakfast"], diet: "veg", icon: "🥞", region: "South" },
  { id: "uttapam", name: "Uttapam", serving: "1 piece", kcal: 190, p: 5, c: 30, f: 5, meal: ["breakfast"], diet: "veg", icon: "🫓", region: "South" },
  { id: "medu-vada", name: "Medu Vada", serving: "2 pieces", kcal: 220, p: 7, c: 22, f: 12, meal: ["breakfast", "snack"], diet: "veg", icon: "🍩", region: "South" },
  { id: "sambar", name: "Sambar", serving: "1 bowl (200g)", kcal: 90, p: 4, c: 14, f: 2, meal: ["breakfast", "lunch", "dinner"], diet: "veg", icon: "🍲", region: "South" },
  { id: "coconut-chutney", name: "Coconut Chutney", serving: "2 tbsp", kcal: 60, p: 1, c: 3, f: 5, meal: ["breakfast"], diet: "veg", icon: "🥥", region: "South" },
  { id: "poha", name: "Poha", serving: "1 plate", kcal: 180, p: 4, c: 32, f: 4, meal: ["breakfast", "snack"], diet: "veg", icon: "🍚", region: "West" },
  { id: "upma", name: "Upma", serving: "1 bowl", kcal: 200, p: 5, c: 32, f: 6, meal: ["breakfast"], diet: "veg", icon: "🥣", region: "South" },
  { id: "pongal", name: "Ven Pongal", serving: "1 bowl", kcal: 240, p: 7, c: 36, f: 8, meal: ["breakfast"], diet: "veg", icon: "🥣", region: "South" },
  { id: "paratha", name: "Plain Paratha", serving: "1 piece", kcal: 210, p: 4, c: 28, f: 9, meal: ["breakfast", "lunch", "dinner"], diet: "veg", icon: "🫓", region: "North" },
  { id: "aloo-paratha", name: "Aloo Paratha", serving: "1 piece + curd", kcal: 330, p: 7, c: 42, f: 14, meal: ["breakfast"], diet: "veg", icon: "🫓", region: "North" },
  { id: "gobi-paratha", name: "Gobi Paratha", serving: "1 piece", kcal: 280, p: 6, c: 36, f: 12, meal: ["breakfast"], diet: "veg", icon: "🫓", region: "North" },
  { id: "thepla", name: "Methi Thepla", serving: "2 pieces", kcal: 180, p: 5, c: 24, f: 7, meal: ["breakfast", "snack"], diet: "veg", icon: "🫓", region: "West" },
  { id: "dhokla", name: "Khaman Dhokla", serving: "3 pieces", kcal: 160, p: 6, c: 22, f: 5, meal: ["breakfast", "snack"], diet: "veg", icon: "🟨", region: "West" },
  { id: "khandvi", name: "Khandvi", serving: "6 pieces", kcal: 140, p: 5, c: 16, f: 6, meal: ["snack"], diet: "veg", icon: "🟨", region: "West" },
  { id: "bread-omelette", name: "Bread Omelette", serving: "2 slices + 2 eggs", kcal: 320, p: 16, c: 28, f: 16, meal: ["breakfast"], diet: "egg", icon: "🍳", region: "Street" },
  { id: "boiled-eggs", name: "Boiled Eggs", serving: "2 eggs", kcal: 156, p: 13, c: 1, f: 11, meal: ["breakfast", "snack"], diet: "egg", icon: "🥚", region: "All" },
  { id: "besan-chilla", name: "Besan Chilla", serving: "2 chillas", kcal: 220, p: 10, c: 24, f: 8, meal: ["breakfast"], diet: "veg", icon: "🥞", region: "North" },
  { id: "oats-upma", name: "Oats Upma", serving: "1 bowl", kcal: 190, p: 7, c: 28, f: 5, meal: ["breakfast"], diet: "veg", icon: "🥣", region: "All" },
  { id: "moong-chilla", name: "Moong Dal Chilla", serving: "2 chillas", kcal: 200, p: 12, c: 26, f: 4, meal: ["breakfast"], diet: "veg", icon: "🥞", region: "North" },

  { id: "roti", name: "Roti / Chapati", serving: "1 piece (40g)", kcal: 80, p: 3, c: 15, f: 1, meal: ["lunch", "dinner"], diet: "veg", icon: "🫓", region: "North" },
  { id: "phulka", name: "Phulka", serving: "1 piece", kcal: 70, p: 2, c: 14, f: 0.5, meal: ["lunch", "dinner"], diet: "veg", icon: "🫓", region: "North" },
  { id: "naan", name: "Butter Naan", serving: "1 piece", kcal: 260, p: 7, c: 40, f: 8, meal: ["lunch", "dinner"], diet: "veg", icon: "🫓", region: "North" },
  { id: "kulcha", name: "Kulcha", serving: "1 piece", kcal: 220, p: 6, c: 36, f: 6, meal: ["lunch"], diet: "veg", icon: "🫓", region: "North" },
  { id: "steamed-rice", name: "Steamed Rice", serving: "1 cup (150g)", kcal: 200, p: 4, c: 44, f: 0.5, meal: ["lunch", "dinner"], diet: "veg", icon: "🍚", region: "All" },
  { id: "jeera-rice", name: "Jeera Rice", serving: "1 cup", kcal: 240, p: 4, c: 42, f: 6, meal: ["lunch", "dinner"], diet: "veg", icon: "🍚", region: "North" },
  { id: "curd-rice", name: "Curd Rice", serving: "1 bowl", kcal: 220, p: 6, c: 36, f: 5, meal: ["lunch", "dinner"], diet: "veg", icon: "🍚", region: "South" },
  { id: "lemon-rice", name: "Lemon Rice", serving: "1 bowl", kcal: 230, p: 4, c: 38, f: 7, meal: ["lunch"], diet: "veg", icon: "🍚", region: "South" },
  { id: "khichdi", name: "Moong Khichdi", serving: "1 bowl", kcal: 210, p: 8, c: 36, f: 4, meal: ["lunch", "dinner"], diet: "veg", icon: "🥣", region: "All" },
  { id: "dal-tadka", name: "Dal Tadka", serving: "1 bowl", kcal: 150, p: 9, c: 20, f: 4, meal: ["lunch", "dinner"], diet: "veg", icon: "🍲", region: "North" },
  { id: "dal-fry", name: "Dal Fry", serving: "1 bowl", kcal: 180, p: 9, c: 20, f: 7, meal: ["lunch", "dinner"], diet: "veg", icon: "🍲", region: "North" },
  { id: "sambar-rice", name: "Sambar Rice", serving: "1 plate", kcal: 280, p: 8, c: 48, f: 5, meal: ["lunch"], diet: "veg", icon: "🍚", region: "South" },
  { id: "rasam", name: "Tomato Rasam", serving: "1 bowl", kcal: 45, p: 2, c: 8, f: 1, meal: ["lunch", "dinner"], diet: "veg", icon: "🍵", region: "South" },
  { id: "rajma", name: "Rajma Masala", serving: "1 bowl", kcal: 230, p: 12, c: 32, f: 6, meal: ["lunch", "dinner"], diet: "veg", icon: "🍛", region: "North" },
  { id: "chole", name: "Chole Masala", serving: "1 bowl", kcal: 250, p: 11, c: 36, f: 7, meal: ["lunch", "dinner"], diet: "veg", icon: "🍛", region: "North" },
  { id: "chole-bhature", name: "Chole Bhature", serving: "1 bhatura + chole", kcal: 450, p: 12, c: 58, f: 18, meal: ["lunch"], diet: "veg", icon: "🥙", region: "North" },
  { id: "palak-paneer", name: "Palak Paneer", serving: "1 bowl", kcal: 280, p: 14, c: 10, f: 20, meal: ["lunch", "dinner"], diet: "veg", icon: "🥬", region: "North" },
  { id: "paneer-butter", name: "Paneer Butter Masala", serving: "1 bowl", kcal: 400, p: 16, c: 14, f: 32, meal: ["lunch", "dinner"], diet: "veg", icon: "🧀", region: "North" },
  { id: "kadai-paneer", name: "Kadai Paneer", serving: "1 bowl", kcal: 320, p: 15, c: 12, f: 24, meal: ["lunch", "dinner"], diet: "veg", icon: "🧀", region: "North" },
  { id: "shahi-paneer", name: "Shahi Paneer", serving: "1 bowl", kcal: 380, p: 14, c: 14, f: 30, meal: ["dinner"], diet: "veg", icon: "🧀", region: "North" },
  { id: "mixed-veg", name: "Mixed Vegetable Curry", serving: "1 bowl", kcal: 130, p: 4, c: 16, f: 6, meal: ["lunch", "dinner"], diet: "veg", icon: "🥗", region: "All" },
  { id: "aloo-gobi", name: "Aloo Gobi", serving: "1 bowl", kcal: 170, p: 4, c: 22, f: 8, meal: ["lunch", "dinner"], diet: "veg", icon: "🥦", region: "North" },
  { id: "baingan-bharta", name: "Baingan Bharta", serving: "1 bowl", kcal: 150, p: 3, c: 14, f: 9, meal: ["lunch", "dinner"], diet: "veg", icon: "🍆", region: "North" },
  { id: "bhindi-masala", name: "Bhindi Masala", serving: "1 bowl", kcal: 160, p: 3, c: 12, f: 11, meal: ["lunch", "dinner"], diet: "veg", icon: "🌿", region: "North" },
  { id: "aloo-jeera", name: "Jeera Aloo", serving: "1 bowl", kcal: 180, p: 3, c: 26, f: 8, meal: ["lunch", "dinner"], diet: "veg", icon: "🥔", region: "North" },
  { id: "lauki-sabzi", name: "Lauki Sabzi", serving: "1 bowl", kcal: 90, p: 2, c: 10, f: 4, meal: ["lunch", "dinner"], diet: "veg", icon: "🥒", region: "North" },
  { id: "kadhi-pakora", name: "Kadhi Pakora", serving: "1 bowl", kcal: 220, p: 7, c: 18, f: 13, meal: ["lunch"], diet: "veg", icon: "🍲", region: "North" },
  { id: "malai-kofta", name: "Malai Kofta", serving: "1 bowl", kcal: 380, p: 10, c: 22, f: 28, meal: ["dinner"], diet: "veg", icon: "🍛", region: "North" },
  { id: "veg-biryani", name: "Veg Biryani", serving: "1 plate", kcal: 350, p: 8, c: 52, f: 12, meal: ["lunch", "dinner"], diet: "veg", icon: "🍚", region: "All" },
  { id: "chicken-biryani", name: "Chicken Biryani", serving: "1 plate", kcal: 450, p: 22, c: 52, f: 16, meal: ["lunch", "dinner"], diet: "nonveg", icon: "🍚", region: "Hyderabad" },
  { id: "mutton-biryani", name: "Mutton Biryani", serving: "1 plate", kcal: 520, p: 24, c: 50, f: 22, meal: ["lunch", "dinner"], diet: "nonveg", icon: "🍚", region: "Hyderabad" },
  { id: "egg-biryani", name: "Egg Biryani", serving: "1 plate", kcal: 380, p: 14, c: 50, f: 12, meal: ["lunch", "dinner"], diet: "egg", icon: "🍚", region: "All" },
  { id: "butter-chicken", name: "Butter Chicken", serving: "1 bowl", kcal: 490, p: 28, c: 12, f: 36, meal: ["lunch", "dinner"], diet: "nonveg", icon: "🍗", region: "North" },
  { id: "chicken-curry", name: "Chicken Curry", serving: "1 bowl", kcal: 280, p: 26, c: 8, f: 16, meal: ["lunch", "dinner"], diet: "nonveg", icon: "🍗", region: "All" },
  { id: "chicken-tikka", name: "Chicken Tikka (4 pcs)", serving: "4 pieces", kcal: 240, p: 28, c: 4, f: 12, meal: ["snack", "dinner"], diet: "nonveg", icon: "🍢", region: "North" },
  { id: "tandoori-chicken", name: "Tandoori Chicken", serving: "2 pieces", kcal: 260, p: 32, c: 4, f: 12, meal: ["dinner"], diet: "nonveg", icon: "🍗", region: "North" },
  { id: "fish-curry", name: "Fish Curry", serving: "1 bowl", kcal: 220, p: 22, c: 6, f: 12, meal: ["lunch", "dinner"], diet: "nonveg", icon: "🐟", region: "Coastal" },
  { id: "fish-fry", name: "Fish Fry", serving: "1 piece", kcal: 200, p: 18, c: 6, f: 12, meal: ["lunch", "dinner"], diet: "nonveg", icon: "🐟", region: "Coastal" },
  { id: "prawn-masala", name: "Prawn Masala", serving: "1 bowl", kcal: 240, p: 20, c: 8, f: 14, meal: ["lunch", "dinner"], diet: "nonveg", icon: "🦐", region: "Coastal" },
  { id: "egg-curry", name: "Egg Curry", serving: "2 eggs + gravy", kcal: 260, p: 14, c: 10, f: 18, meal: ["lunch", "dinner"], diet: "egg", icon: "🍳", region: "All" },
  { id: "mutton-curry", name: "Mutton Curry", serving: "1 bowl", kcal: 340, p: 24, c: 8, f: 24, meal: ["lunch", "dinner"], diet: "nonveg", icon: "🍖", region: "All" },
  { id: "keema", name: "Keema Matar", serving: "1 bowl", kcal: 300, p: 22, c: 10, f: 20, meal: ["lunch", "dinner"], diet: "nonveg", icon: "🍖", region: "North" },
  { id: "veg-thali", name: "Veg Thali", serving: "1 full thali", kcal: 650, p: 18, c: 90, f: 22, meal: ["lunch", "dinner"], diet: "veg", icon: "🍽️", region: "All" },
  { id: "nonveg-thali", name: "Non-Veg Thali", serving: "1 full thali", kcal: 820, p: 32, c: 88, f: 34, meal: ["lunch", "dinner"], diet: "nonveg", icon: "🍽️", region: "All" },
  { id: "curd", name: "Dahi / Curd", serving: "1 katori (100g)", kcal: 60, p: 3, c: 5, f: 3, meal: ["lunch", "dinner", "snack"], diet: "veg", icon: "🥛", region: "All" },
  { id: "raita", name: "Boondi Raita", serving: "1 bowl", kcal: 90, p: 3, c: 10, f: 4, meal: ["lunch", "dinner"], diet: "veg", icon: "🥛", region: "North" },
  { id: "salad", name: "Kachumber Salad", serving: "1 bowl", kcal: 40, p: 1, c: 8, f: 0, meal: ["lunch", "dinner"], diet: "veg", icon: "🥗", region: "All" },
  { id: "papad", name: "Roasted Papad", serving: "1 piece", kcal: 30, p: 1, c: 5, f: 0.5, meal: ["lunch", "dinner"], diet: "veg", icon: "🫓", region: "All" },
  { id: "pickle", name: "Achar (pickle)", serving: "1 tsp", kcal: 20, p: 0, c: 1, f: 2, meal: ["lunch", "dinner"], diet: "veg", icon: "🌶️", region: "All" },

  { id: "samosa", name: "Samosa", serving: "1 piece", kcal: 250, p: 4, c: 28, f: 14, meal: ["snack"], diet: "veg", icon: "🥟", region: "Street" },
  { id: "pakora", name: "Mixed Pakora", serving: "4 pieces", kcal: 200, p: 5, c: 18, f: 12, meal: ["snack"], diet: "veg", icon: "🧆", region: "Street" },
  { id: "paneer-pakora", name: "Paneer Pakora", serving: "4 pieces", kcal: 280, p: 10, c: 16, f: 18, meal: ["snack"], diet: "veg", icon: "🧀", region: "Street" },
  { id: "bhel-puri", name: "Bhel Puri", serving: "1 plate", kcal: 180, p: 4, c: 32, f: 4, meal: ["snack"], diet: "veg", icon: "🥗", region: "Street" },
  { id: "pani-puri", name: "Pani Puri", serving: "6 pieces", kcal: 150, p: 3, c: 28, f: 3, meal: ["snack"], diet: "veg", icon: "⚪", region: "Street" },
  { id: "sev-puri", name: "Sev Puri", serving: "6 pieces", kcal: 220, p: 4, c: 30, f: 10, meal: ["snack"], diet: "veg", icon: "🟠", region: "Street" },
  { id: "vada-pav", name: "Vada Pav", serving: "1 piece", kcal: 290, p: 6, c: 40, f: 12, meal: ["snack"], diet: "veg", icon: "🍔", region: "Mumbai" },
  { id: "pav-bhaji", name: "Pav Bhaji", serving: "2 pav + bhaji", kcal: 400, p: 9, c: 52, f: 16, meal: ["snack", "dinner"], diet: "veg", icon: "🍔", region: "Mumbai" },
  { id: "misal-pav", name: "Misal Pav", serving: "1 plate", kcal: 380, p: 12, c: 48, f: 14, meal: ["breakfast", "snack"], diet: "veg", icon: "🌶️", region: "West" },
  { id: "dabeli", name: "Dabeli", serving: "1 piece", kcal: 250, p: 5, c: 38, f: 8, meal: ["snack"], diet: "veg", icon: "🥪", region: "West" },
  { id: "kathi-roll", name: "Veg Kathi Roll", serving: "1 roll", kcal: 320, p: 8, c: 40, f: 14, meal: ["snack", "lunch"], diet: "veg", icon: "🌯", region: "East" },
  { id: "chicken-roll", name: "Chicken Kathi Roll", serving: "1 roll", kcal: 380, p: 18, c: 38, f: 16, meal: ["snack", "lunch"], diet: "nonveg", icon: "🌯", region: "East" },
  { id: "momos-veg", name: "Veg Momos", serving: "8 pieces steamed", kcal: 220, p: 7, c: 36, f: 5, meal: ["snack"], diet: "veg", icon: "🥟", region: "East" },
  { id: "momos-chicken", name: "Chicken Momos", serving: "8 pieces steamed", kcal: 260, p: 14, c: 32, f: 8, meal: ["snack"], diet: "nonveg", icon: "🥟", region: "East" },
  { id: "samosa-chaat", name: "Samosa Chaat", serving: "1 plate", kcal: 320, p: 8, c: 36, f: 16, meal: ["snack"], diet: "veg", icon: "🥗", region: "Street" },
  { id: "corn-chaat", name: "Corn Chaat", serving: "1 bowl", kcal: 140, p: 4, c: 24, f: 3, meal: ["snack"], diet: "veg", icon: "🌽", region: "Street" },
  { id: "roasted-makhana", name: "Roasted Makhana", serving: "1 cup", kcal: 90, p: 3, c: 16, f: 1, meal: ["snack"], diet: "veg", icon: "⚪", region: "All" },
  { id: "sprouts", name: "Sprouts Chaat", serving: "1 bowl", kcal: 120, p: 8, c: 18, f: 2, meal: ["breakfast", "snack"], diet: "veg", icon: "🌱", region: "All" },
  { id: "peanuts", name: "Roasted Peanuts", serving: "30g", kcal: 170, p: 7, c: 6, f: 14, meal: ["snack"], diet: "veg", icon: "🥜", region: "All" },
  { id: "murukku", name: "Murukku", serving: "4 pieces", kcal: 180, p: 3, c: 20, f: 10, meal: ["snack"], diet: "veg", icon: "🥨", region: "South" },

  { id: "gulab-jamun", name: "Gulab Jamun", serving: "2 pieces", kcal: 280, p: 4, c: 42, f: 12, meal: ["snack"], diet: "veg", icon: "🟤", region: "All", tag: "sweet" },
  { id: "rasgulla", name: "Rasgulla", serving: "2 pieces", kcal: 180, p: 4, c: 36, f: 2, meal: ["snack"], diet: "veg", icon: "⚪", region: "East", tag: "sweet" },
  { id: "jalebi", name: "Jalebi", serving: "2 pieces", kcal: 220, p: 2, c: 40, f: 8, meal: ["breakfast", "snack"], diet: "veg", icon: "🟠", region: "Street", tag: "sweet" },
  { id: "jalebi-rabri", name: "Jalebi + Rabri", serving: "1 plate", kcal: 380, p: 6, c: 52, f: 16, meal: ["snack"], diet: "veg", icon: "🟠", region: "Street", tag: "sweet" },
  { id: "kheer", name: "Rice Kheer", serving: "1 bowl", kcal: 220, p: 6, c: 32, f: 8, meal: ["snack"], diet: "veg", icon: "🥣", region: "All", tag: "sweet" },
  { id: "ladoo", name: "Besan Ladoo", serving: "1 piece", kcal: 160, p: 3, c: 18, f: 8, meal: ["snack"], diet: "veg", icon: "🟡", region: "All", tag: "sweet" },
  { id: "barfi", name: "Kaju Barfi", serving: "1 piece", kcal: 120, p: 2, c: 14, f: 6, meal: ["snack"], diet: "veg", icon: "⬜", region: "All", tag: "sweet" },
  { id: "halwa", name: "Gajar Halwa", serving: "1 katori", kcal: 240, p: 4, c: 32, f: 12, meal: ["snack"], diet: "veg", icon: "🥕", region: "North", tag: "sweet" },
  { id: "mysore-pak", name: "Mysore Pak", serving: "1 piece", kcal: 180, p: 3, c: 16, f: 12, meal: ["snack"], diet: "veg", icon: "🟨", region: "South", tag: "sweet" },
  { id: "payasam", name: "Payasam", serving: "1 bowl", kcal: 200, p: 5, c: 30, f: 7, meal: ["snack"], diet: "veg", icon: "🥣", region: "South", tag: "sweet" },

  { id: "masala-chai", name: "Masala Chai", serving: "1 cup with milk & sugar", kcal: 90, p: 2, c: 14, f: 3, meal: ["breakfast", "snack"], diet: "veg", icon: "☕", region: "All", tag: "drink" },
  { id: "filter-coffee", name: "Filter Coffee", serving: "1 cup", kcal: 50, p: 2, c: 6, f: 2, meal: ["breakfast", "snack"], diet: "veg", icon: "☕", region: "South", tag: "drink" },
  { id: "lassi-sweet", name: "Sweet Lassi", serving: "1 glass", kcal: 180, p: 6, c: 28, f: 5, meal: ["lunch", "snack"], diet: "veg", icon: "🥛", region: "North", tag: "drink" },
  { id: "lassi-salted", name: "Salted Lassi", serving: "1 glass", kcal: 110, p: 6, c: 10, f: 4, meal: ["lunch"], diet: "veg", icon: "🥛", region: "North", tag: "drink" },
  { id: "chaas", name: "Chaas / Buttermilk", serving: "1 glass", kcal: 40, p: 3, c: 4, f: 1, meal: ["lunch", "dinner"], diet: "veg", icon: "🥛", region: "West", tag: "drink" },
  { id: "nimbu-pani", name: "Nimbu Pani", serving: "1 glass", kcal: 60, p: 0, c: 15, f: 0, meal: ["snack"], diet: "veg", icon: "🍋", region: "All", tag: "drink" },
  { id: "coconut-water", name: "Coconut Water", serving: "1 glass", kcal: 45, p: 1, c: 9, f: 0, meal: ["snack"], diet: "veg", icon: "🥥", region: "Coastal", tag: "drink" },
  { id: "mango-lassi", name: "Mango Lassi", serving: "1 glass", kcal: 220, p: 6, c: 38, f: 5, meal: ["snack"], diet: "veg", icon: "🥭", region: "North", tag: "drink" },
  { id: "badam-milk", name: "Badam Milk", serving: "1 glass", kcal: 180, p: 6, c: 22, f: 8, meal: ["snack"], diet: "veg", icon: "🥛", region: "All", tag: "drink" },
  { id: "sugarcane", name: "Sugarcane Juice", serving: "1 glass", kcal: 180, p: 0, c: 45, f: 0, meal: ["snack"], diet: "veg", icon: "🧃", region: "Street", tag: "drink" },

  { id: "banana", name: "Banana", serving: "1 medium", kcal: 90, p: 1, c: 23, f: 0, meal: ["breakfast", "snack"], diet: "veg", icon: "🍌", region: "All" },
  { id: "apple", name: "Apple", serving: "1 medium", kcal: 80, p: 0, c: 21, f: 0, meal: ["snack"], diet: "veg", icon: "🍎", region: "All" },
  { id: "mango", name: "Mango", serving: "1 medium", kcal: 150, p: 1, c: 36, f: 1, meal: ["snack"], diet: "veg", icon: "🥭", region: "All" },
  { id: "papaya", name: "Papaya", serving: "1 bowl", kcal: 70, p: 1, c: 17, f: 0, meal: ["breakfast", "snack"], diet: "veg", icon: "🟠", region: "All" },
  { id: "orange", name: "Orange", serving: "1 medium", kcal: 60, p: 1, c: 15, f: 0, meal: ["snack"], diet: "veg", icon: "🍊", region: "All" },
  { id: "pomegranate", name: "Pomegranate", serving: "1 bowl", kcal: 80, p: 1, c: 18, f: 1, meal: ["snack"], diet: "veg", icon: "🔴", region: "All" },
  { id: "buttermilk-oats", name: "Fruit + Curd Bowl", serving: "1 bowl", kcal: 150, p: 6, c: 24, f: 3, meal: ["breakfast", "snack"], diet: "veg", icon: "🍓", region: "All" }
];

window.MEAL_COMBOS = [
  { id: "si-breakfast", name: "South Indian Breakfast", meal: "breakfast", diet: "veg", items: ["idli", "sambar", "coconut-chutney"], note: "Light and filling" },
  { id: "dosa-combo", name: "Dosa Plate", meal: "breakfast", diet: "veg", items: ["dosa", "sambar", "coconut-chutney"], note: "Crisp dosa with sides" },
  { id: "poha-chai", name: "Poha & Chai", meal: "breakfast", diet: "veg", items: ["poha", "masala-chai"], note: "Quick weekday breakfast" },
  { id: "paratha-dahi", name: "Paratha Breakfast", meal: "breakfast", diet: "veg", items: ["aloo-paratha", "curd"], note: "North Indian classic" },
  { id: "protein-morning", name: "High Protein Morning", meal: "breakfast", diet: "egg", items: ["besan-chilla", "boiled-eggs", "masala-chai"], note: "Keeps you full longer" },
  { id: "sprouts-fruit", name: "Light Start", meal: "breakfast", diet: "veg", items: ["sprouts", "papaya", "filter-coffee"], note: "Lower calorie morning" },
  { id: "north-thali", name: "Home-style North Plate", meal: "lunch", diet: "veg", items: ["roti", "roti", "dal-tadka", "mixed-veg", "curd", "salad"], note: "Balanced everyday thali" },
  { id: "rajma-chawal", name: "Rajma Chawal", meal: "lunch", diet: "veg", items: ["steamed-rice", "rajma", "salad", "chaas"], note: "Comfort lunch" },
  { id: "sambar-rice-combo", name: "Sambar Rice Meal", meal: "lunch", diet: "veg", items: ["sambar-rice", "papad", "curd"], note: "South lunch" },
  { id: "chole-roti", name: "Chole Roti", meal: "lunch", diet: "veg", items: ["roti", "roti", "chole", "salad"], note: "Punjabi favourite" },
  { id: "fish-rice", name: "Fish Curry Rice", meal: "lunch", diet: "nonveg", items: ["steamed-rice", "fish-curry", "salad"], note: "Coastal lunch" },
  { id: "chicken-roti", name: "Chicken Curry Meal", meal: "lunch", diet: "nonveg", items: ["roti", "roti", "chicken-curry", "salad"], note: "Protein-forward" },
  { id: "khichdi-light", name: "Khichdi Dinner", meal: "dinner", diet: "veg", items: ["khichdi", "curd", "papad"], note: "Easy on the stomach" },
  { id: "palak-roti", name: "Palak Paneer Dinner", meal: "dinner", diet: "veg", items: ["roti", "roti", "palak-paneer", "salad"], note: "Iron + protein" },
  { id: "curd-rice-n", name: "Curd Rice Night", meal: "dinner", diet: "veg", items: ["curd-rice", "pickle"], note: "Light south dinner" },
  { id: "tandoori-night", name: "Tandoori Plate", meal: "dinner", diet: "nonveg", items: ["tandoori-chicken", "roti", "salad"], note: "Lower gravy, high protein" },
  { id: "evening-bhel", name: "Evening Chaat", meal: "snack", diet: "veg", items: ["bhel-puri", "nimbu-pani"], note: "Street-style, not too heavy" },
  { id: "makhana-chai", name: "Tea-time Light", meal: "snack", diet: "veg", items: ["roasted-makhana", "masala-chai"], note: "Office snack" },
  { id: "fruit-dahi", name: "Fruit & Curd", meal: "snack", diet: "veg", items: ["banana", "curd"], note: "Simple and filling" }
];

window.FOOD_BY_ID = Object.fromEntries(window.INDIAN_FOODS.map((f) => [f.id, f]));
